version: "3.8"
services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    build:
      context: .
      dockerfile: dockerfile.redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_volume_data:
