version: "3.8"
services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_volume_data:/data

volumes:
  redis_volume_data:
