version: '3.8'
services:
  api:
    build: .
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379
      - DATABASE_CONNECTION_OPTIONS={'type':'mongodb','host':'mongo','port':27017,'username':'matteo_db_user','password':'XZnIjkcH4hEjSnhX','database':'mycontacts-backend','logging':false}
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_volume_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=matteo_db_user
      - MONGO_INITDB_ROOT_PASSWORD=XZnIjkcH4hEjSnhX

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    expose:
      - '6379'

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - redis_insight_volume_data:/db
    depends_on:
      - redis

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  mongo_volume_data:
