version: "3.8"
services:
  api:
    build: .
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - ACCESS_TOKEN_SECRET=matteo123
      - REDIS_URL=redis://redis:6379
      - DATABASE_CONNECTION_OPTIONS={"type":"postgres","host":"postgres","port":5432,"username":"postgres","password":"matteo_db_password","database":"mycontacts-backend","logging":false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "5002"
    networks:
      - net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=matteo_db_password
      - POSTGRES_DB=mycontacts-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
    networks:
      - net
    expose:
      - "6379"

volumes:
  redis_volume_data:
  postgres_volume_data:

networks:
  net:
    driver: bridge