version: '3.8'
services:
  api:
    build: .
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    expose:
      - '6379'

volumes:
  redis_volume_data:
