apiVersion: v1
kind: Service
metadata:
  name: backend-contacts-1-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: backend-contacts-1
  type: LoadBalancer
status:
  loadBalancer: {}
