apiVersion: v1
kind: Service
metadata:
  name: express-project-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5002
  selector:
    app: express-project
  type: LoadBalancer
status:
  loadBalancer: {}
